// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"database/sql"
	"git.dustess.com/mk-base/log"
	"github.com/bxcodec/go-clean-arch/internal/article/delivery/http"
	"github.com/bxcodec/go-clean-arch/internal/article/repository/mysql"
	"github.com/bxcodec/go-clean-arch/internal/article/usecase"
	mysql2 "github.com/bxcodec/go-clean-arch/internal/author/repository/mysql"
	"github.com/gin-gonic/gin"
	"time"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

// InitApp init kratos application.
func InitApp(engine *gin.Engine, db *sql.DB, loggerTrace *log.LoggerTrace, duration time.Duration) error {
	articleRepository := mysql.NewMysqlArticleRepository(db, loggerTrace)
	authorRepository := mysql2.NewMysqlAuthorRepository(db, loggerTrace)
	articleUsecase := usecase.NewArticleUsecase(articleRepository, authorRepository, duration, loggerTrace)
	error2 := http.NewArticleHandler(engine, articleUsecase, loggerTrace)
	return error2
}
